server:
  port: 8084
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true

spring:
  application:
    name: web-service
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  mvc:
    static-path-pattern: /static/**

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://admin:password@localhost:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG
    com.blogapp: DEBUG