server:
  port: ${PORT:8084}
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true

spring:
  application:
    name: web-service
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  mvc:
    static-path-pattern: /static/**

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:password}@${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/
  instance:
    hostname: ${HOSTNAME:web-service}

logging:
  level:
    org.springframework.security: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:INFO}
    com.blogapp: ${LOGGING_LEVEL_COM_BLOGAPP:INFO}