server:
  port: 8080

spring:
  application:
    name: api-gateway
  webflux:
    static-path-pattern: /**
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # User Service Routes
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/auth/**
        # Post Service Routes
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**, /api/comments/**
        # Feed Service Routes
        - id: feed-service
          uri: lb://feed-service
          predicates:
            - Path=/api/feed/**
  web:
    resources:
      static-locations: classpath:/static/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics