spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practos_9_proslushivanie_musiki
    username: postgres
    password: villem
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

logging:
  level:
    com.blogapp: DEBUG
    org.hibernate.SQL: DEBUG