server:
  port: ${PORT:8081}

spring:
  application:
    name: user-service
  config:
    import: optional:classpath:application-common.yml

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:password}@${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:user-service}

management:
  endpoints:
    web:
      exposure:
        include: health,info