server:
  port: 8083

spring:
  application:
    name: feed-service
  datasource:
    url: jdbc:postgresql://localhost:5432/practos_9_proslushivanie_musiki
    username: postgres
    password: villem
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://admin:password@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.blogapp: DEBUG
    org.hibernate.SQL: DEBUG